import { Project, Parliamentarian, Vote, HistoricalData, Candidate } from './types';

export const mockProjects: Project[] = [
  {
    id: 'PL-1234-2023',
    title: 'PL 1234/2023 - Igualdade Salarial',
    theme: 'Igualdade Salarial',
    summary: 'Estabelece medidas para garantir a igualdade salarial e de critérios remuneratórios entre mulheres e homens.',
    date: '15/05/2023',
    status: 'Aprovado',
    house: 'Câmara',
    year: 2023,
  },
  {
    id: 'PL-5678-2022',
    title: 'PL 5678/2022 - Combate à Violência Doméstica',
    theme: 'Violência Doméstica',
    summary: 'Altera a Lei Maria da Penha para ampliar as medidas protetivas de urgência.',
    date: '10/11/2022',
    status: 'Aprovado',
    house: 'Câmara',
    year: 2022,
  },
  {
    id: 'PL-9012-2023',
    title: 'PL 9012/2023 - Dignidade Menstrual',
    theme: 'Saúde da Mulher',
    summary: 'Institui o Programa de Proteção e Promoção da Saúde Menstrual.',
    date: '22/03/2023',
    status: 'Rejeitado',
    house: 'Senado',
    year: 2023,
  },
];

export const mockParliamentarians: Parliamentarian[] = [
  {
    id: '1',
    name: 'Tabata Amaral',
    party: 'PSB',
    state: 'SP',
    photoUrl: 'https://www.camara.leg.br/internet/deputado/bandep/204534.jpg',
    mandates: 2,
    gender: 'Feminino',
    favorableVotes: 15,
    againstVotes: 2,
    abstentions: 1,
    score: 92,
    commissions: ['Educação', 'Defesa dos Direitos da Mulher'],
    projects: [
      { id: 'PL-1', title: 'Incentivo à Ciência para Meninas', theme: 'Educação' },
      { id: 'PL-2', title: 'Combate à Pobreza Menstrual', theme: 'Saúde' },
    ],
    attendanceRate: 96,
    totalAnalyzedVotes: 32,
  },
  {
    id: '2',
    name: 'Erika Hilton',
    party: 'PSOL',
    state: 'SP',
    photoUrl: 'https://www.camara.leg.br/internet/deputado/bandep/220645.jpg',
    mandates: 1,
    gender: 'Feminino',
    favorableVotes: 18,
    againstVotes: 0,
    abstentions: 0,
    score: 98,
    commissions: ['Direitos Humanos', 'Minorias'],
    projects: [
      { id: 'PL-3', title: 'Proteção a Mulheres Trans', theme: 'Direitos Humanos' },
    ],
    attendanceRate: 98,
    totalAnalyzedVotes: 32,
  },
  {
    id: '3',
    name: 'Arthur Lira',
    party: 'PP',
    state: 'AL',
    photoUrl: 'https://www.camara.leg.br/internet/deputado/bandep/160541.jpg',
    mandates: 4,
    gender: 'Masculino',
    favorableVotes: 10,
    againstVotes: 5,
    abstentions: 3,
    score: 65,
    commissions: ['Mesa Diretora'],
    projects: [],
    attendanceRate: 85,
    totalAnalyzedVotes: 32,
  },
  {
    id: '4',
    name: 'Bia Kicis',
    party: 'PL',
    state: 'DF',
    photoUrl: 'https://www.camara.leg.br/internet/deputado/bandep/204374.jpg',
    mandates: 2,
    gender: 'Feminino',
    favorableVotes: 5,
    againstVotes: 12,
    abstentions: 2,
    score: 35,
    commissions: ['CCJ'],
    projects: [],
    attendanceRate: 72,
    totalAnalyzedVotes: 32,
  },
  {
    id: '5',
    name: 'Benedita da Silva',
    party: 'PT',
    state: 'RJ',
    photoUrl: 'https://www.camara.leg.br/internet/deputado/bandep/73701.jpg',
    mandates: 6,
    gender: 'Feminino',
    favorableVotes: 20,
    againstVotes: 1,
    abstentions: 0,
    score: 95,
    commissions: ['Cultura'],
    projects: [{ id: 'PL-4', title: 'Cotas para Mulheres Negras', theme: 'Igualdade' }],
    attendanceRate: 94,
    totalAnalyzedVotes: 32,
  },
];

export const mockVotes: Record<string, Vote[]> = {
  'PL-1234-2023': [
    { parliamentarianId: '1', name: 'Tabata Amaral', party: 'PSB', state: 'SP', vote: 'Sim' },
    { parliamentarianId: '2', name: 'Erika Hilton', party: 'PSOL', state: 'SP', vote: 'Sim' },
    { parliamentarianId: '3', name: 'Arthur Lira', party: 'PP', state: 'AL', vote: 'Sim' },
    { parliamentarianId: '4', name: 'Bia Kicis', party: 'PL', state: 'DF', vote: 'Não' },
    { parliamentarianId: '5', name: 'Benedita da Silva', party: 'PT', state: 'RJ', vote: 'Sim' },
  ],
};

export const mockHistoricalData: HistoricalData[] = [
  { year: 2010, percentage: 8.9 },
  { year: 2014, percentage: 9.9 },
  { year: 2018, percentage: 15.0 },
  { year: 2022, percentage: 17.7 },
];

export const mockCandidates: Candidate[] = [
  { id: 'c1', name: 'Maria Silva', party: 'PT', state: 'SP', city: 'São Paulo', office: 'Prefeita', votes: 1250000, status: 'Eleita' },
  { id: 'c2', name: 'Ana Souza', party: 'PSDB', state: 'RJ', city: 'Rio de Janeiro', office: 'Vereadora', votes: 45000, status: 'Eleita' },
  { id: 'c3', name: 'Julia Lima', party: 'MDB', state: 'MG', city: 'Belo Horizonte', office: 'Prefeita', votes: 320000, status: 'Não Eleita' },
];
